#!/bin/bash
(ls -a | grep -v '^$' | awk '{if ($0 == ".") print $0; else if ($0 == "..") print $0; else print $0}' | sort -V | awk '{if (system("[ -d \""$0"\" ]") == 0) print $0"/"; else print $0}' | paste -sd ",") && echo
